version = 1

test_patterns = [
  "tests/test_*.py"
]

exclude_patterns = [
  "django_cas_ng/migrations/**",
  "docs/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

