language: python

cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.5
      env: TOXENV=py35-django20
    - python: 3.6
      env: TOXENV=py36-django20
    - python: 3.7
      env: TOXENV=py37-django20
    - python: 3.5
      env: TOXENV=py35-django21
    - python: 3.6
      env: TOXENV=py36-django21
    - python: 3.7
      env: TOXENV=py37-django21
    - python: 3.5
      env: TOXENV=py35-django22
    - python: 3.6
      env: TOXENV=py36-django22
    - python: 3.7
      env: TOXENV=py37-django22
    - python: 3.8
      env: TOXENV=py38-django22
    - python: 3.6
      env: TOXENV=py36-django30
    - python: 3.7
      env: TOXENV=py37-django30
    - python: 3.8
      env: TOXENV=py38-django30
    - python: 3.6
      env: TOXENV=py36-djangomaster
    - python: 3.7
      env: TOXENV=py37-djangomaster
    - python: 3.8
      env: TOXENV=py38-djangomaster
    - env: TOXENV=flake8
    - env: TOXENV=isort
  allow_failures:
    - env: TOXENV=py36-djangomaster
    - env: TOXENV=py37-djangomaster
    - env: TOXENV=py38-djangomaster

install:
  - pip install tox
  - pip install codecov

script:
  - tox

# Push the results back to codecov
after_success:
  - codecov
